### ISSUE TITLE
Open source list

### ISSUE THREAD

**Issue by NithinSS** [FossMec/Welcome#3]
Shouldn't there be a list of open source softwares and normal FOSS alternatives like GNU/Linux for Windows , GIMP for Adobe Photoshop etc..

**Comment by ashwin-nair98** [comment]
We could add them later as another file maybe?
It requires quite a bit of research to find out good alternatives to all popular applications.

**Comment by guyandtheworld** [comment]
According to my knowledge @harirajk was working on it.

**Comment by NithinSS** [comment]
merge the work here

**Comment by guyandtheworld** [comment]
#8
